Main: Main.o Persona.o Object.o Employee.o ADTList.o VSArrayList.o
	g++ Main.o Persona.o Object.o Employee.o ADTList.o VSArrayList.o -o Main

Main.o: Main.cpp Persona.h Object.h Employee.h ADTList.h VSArrayList.h
	g++ -c Main.cpp

Persona.o: Object.h Persona.h Persona.cpp
	g++ -c Persona.cpp

Object.o: Object.h Object.cpp
	g++ -c Object.cpp

Employee.o: Persona.h Employee.h Employee.cpp
	g++ -c Employee.cpp

ADTList.o: ADTList.h ADTList.cpp
	g++ -c ADTList.cpp

VSArrayList.o: ADTList.h VSArrayList.h VSArrayList.cpp
	g++ -c VSArrayList.cpp

Clean:
	rm -f *.o Main
